[package]
name = "ray-tracer-challenge"
version = "0.1.0"
authors = ["nyctef <nyctef@nyctef.com>"]

[lib]
name = "rtc"
path ="./src/lib.rs"

[dependencies]
float-cmp = "0.6.0"
impl_ops = "0.1.1"
nalgebra = "0.18"
approx = "0.3.2"
png = "0.15.2"

